### ISSUE TITLE
[Feature] Add TubeMQ Command Tools

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4972]
### Description

like `tubectl`, we can create/delete topic, produce/consume message.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DavidYoungdj** [comment]
@dockerzhang Hi,I want to do this task.

**Comment by DavidYoungdj** [comment]
### Purpose
  Add TubeMQ command tools like the kafka command tools.We can create/delete the topics,produce/consume the message.
### Plan
#### About creating / deleting a topic

1. Set parameters to add / remove topics based on the type of parameter passed in.
2. Call the client's code to create the admin of the client
3. Check whether the partitions are correct and handle other exceptions. For example, the partitions must be greater than 0
4. Make the network request and have the server of the Controller role accept the request processing logic
5. Perform calibration check
6. The data is stored in the master node

#### Generating / consume information

- Producer

1. Set necessary parameters, such as obtaining server metadata, conditions for successfully writing data, and retry times
2. Create TubeMQproducer
3. Determine the topic, key, and message body to send
4. Send the message

- Consumer

1. If the topic is empty, the exception is handled. Otherwise, the subscription status is reset and the subscription information and metadata are updated
2. Ensuring thread Safety
3. It can communicate with Cluster, register Consumer with Coordinator, and pull and update metadata
4. Sends all requests to be sent and processes all received responses

**Comment by dockerzhang** [comment]
@DavidYoungdj do you still work on this issue?

**Comment by DavidYoungdj** [comment]
Sorry for that I'm not work on this issue.I need to focus on my course now.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/inlong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月19日(星期一) 下午4:34
***@***.***&gt;;
抄送:&nbsp;"骑马与砍杀@***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/inlong] [Feature] Add TubeMQ Command Tools (Issue #4972)





 
@DavidYoungdj do you still work on this issue?

**Comment by TheR1sing3un** [comment]
@dockerzhang Hi, I read about this task in https://github.com/Tencent/OpenSourceTalent/issues/39 , I am very intersted in this task. How can I get in touch with you？

**Comment by dockerzhang** [comment]
Open again for new contributors
