### ISSUE TITLE
[Improve][TubeMQ]The storage space used by the offset of TubeMQ broker is too large

### ISSUE THREAD

**Issue by FvvSuu** [apache/inlong#6535]
### Description

The storage space used by the offset of TubeMQ broker is too large.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/53012896/201810458-3d0336d6-4e91-41a6-ad42-200600884369.png">
There are 5~6 consumer groups in the picture

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks @FvvSuu, got it

**Comment by gosonzhang** [comment]
It should be caused by too much duplicate data in the offset records of the storage consumption group: in order to make the records more readable[1], for example, each partition consumption record contains the consumption group name, and each partition repeatedly records the maximum and minimum offsets, as a result, the total data record is bloated too much.

Considering the traversal of the text display, I plan to still use the text to represent the saved historical offset, but perform field key abbreviation and deduplication processing to reduce the length of the total record.

1. https://github.com/apache/inlong/blob/master/inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordInfo.java#L68
![image](https://user-images.githubusercontent.com/14038849/201811778-557ecdb1-2a82-4977-89e5-a4d85fbde77e.png)
