### ISSUE TITLE
[Bug][TubeMQ] The updated version causes the consumer group permissions to be abnormal

### ISSUE THREAD

**Issue by FvvSuu** [apache/inlong#6579]
### What happened

The updated version causes the consumer group permissions to be abnormal

### What you expected to happen

The consumeEnable of some consumer groups becomes false, and the data cannot be consumed.

### How to reproduce

 updated version

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@gosonzhang PTAL, thanks.

**Comment by gosonzhang** [comment]
@FvvSuu, thanks

**Comment by gosonzhang** [comment]
I reproduced this problem in the environment: when adding the authorization information of the consumer group first through the API admin_add_authorized_consumergroup_info, and then adding the filter information of the consumer group throuth the API admin_add_group_filtercond_info, the authorization of the consumer group will be set to STATUS_DISABLE.

The reason for the problem lies in the following implementation points :
![image](https://user-images.githubusercontent.com/14038849/202997358-dc3f825c-0beb-45aa-8e8a-1c7718b6bc35.png)
https://github.com/apache/inlong/blob/master/inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsConsumeCtrlMapperImpl. java#L86

Then, I found that the field processing of the EnableStatus class is not very good, and I will improve it together.

Thanks @FvvSuu again!
