### ISSUE TITLE
[Bug][SDK] Adjusted frame length exceeds occurred when reporting data through the HTTP protocol

### ISSUE THREAD

**Issue by g0715158** [apache/inlong#7766]
### What happened

When using dataproxy-sdk to report data through the http protocol, the following screenshots report errors:

The scenario description is as follows (SDK only reports one piece of data per startup process):

1. This exception will be reported for the first piece of data reported after the creation of the data stream

2. If the data is not reported for a long time, the first piece of data will report this exception when the data is reported again

Guess the reason for this problem is due to the DataProxy's channel management policy configuration for netty

![image](https://user-images.githubusercontent.com/16098391/229442367-94fc3f8b-c606-4db1-bdaa-7926b04c95e1.png)

### What you expected to happen

Normal reporting of messages

### How to reproduce

repair this bug

### Environment

version:1.6.0

### InLong version

1.6.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@gosonzhang PTAL, thanks.

**Comment by gosonzhang** [comment]
Thanks @g0715158, got it!

**Comment by gosonzhang** [comment]
Feedback on the current situation of this problem, I plan to optimize the implementation of the Source side [1] first, and use netty to handle HTTP data access. This issue is temporarily reserved, and it will be tested and verified after integration

1. https://github.com/apache/inlong/issues/7950

**Comment by gosonzhang** [comment]
Judging from this error message, there are several situations:
1. There is an error in the protocol of the message report, such as TCP reporting to the HTTP port, or the packet format is wrong, resulting in an error in recognition;
2. The format of the message report is correct, but an overlong packet is sent

I found new similar problems in my environment, and I feel that there are still problems, and I need to continue to locate them

**Comment by gosonzhang** [comment]
This problem should be caused by [1] changes

When the InLong-SDK obtains the access information of the DataProxy reporting node from the Manager, it needs to carry the reporting protocol that the SDK needs to adopt. If the information is not carried, the Manager will return all the reporting ports supported by the DataProxy; in this case, the SDK will Reporting failure occurs because a reporting node with inconsistent protocols is selected.

I will fix this problem, set different reporting protocols according to the created Sender, and store the cached information separately

1. https://github.com/apache/inlong/issues/6190
