### ISSUE TITLE
[Improve][TubeMQ] Supports the return package type when querying messages

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#8286]
### Description

Currently, the packaging mode of data cannot be determined when pulling data through the interface `/broker.htm?method=admin_snapshot_message`. A field needs to be added to indicate whether the packaging type of data is `inlongMsg`.

The following is the current return info:

```
{
    "result": true,
    "errCode": 200,
    "errMsg": "Success!",
    "dataSet": [{
        "index": 0,
        "data": "DwEAAAGIs9j+JgAAAAEAdGdyb3VwSWQ9dGVzdF9kYXRhcHJveHkmc3RyZWFtSWQ9c3RyZWFtMSZkdD0xNjg1MzQ4ODAzMDU1Jk5vZGVJUD05LjIzLjI4Ljg2JmNudD0xJnJ0PTE2ODY2NDQ1MjI1MzImcnRtcz0xNjg2NjQ0NTIyNTMyAAAAEgEPOAAAAAsxfHdob3xkb2luZw8B"
    }, {
        "index": 1,
        "data": "DwEAAAGIs9lE3QAAAAEAdGdyb3VwSWQ9dGVzdF9kYXRhcHJveHkmc3RyZWFtSWQ9c3RyZWFtMSZkdD0xNjg1MzQ4ODAzMDU1Jk5vZGVJUD05LjIzLjI4Ljg2JmNudD0xJnJ0PTE2ODY2NDQ1NDA2MzYmcnRtcz0xNjg2NjQ0NTQwNjM2AAAAEgEPOAAAAAsxfHdob3xkb2luZw8B"
    }, {
        "index": 2,
        "data": "DwEAAAGItAscngAAAAEAdGdyb3VwSWQ9dGVzdF9kYXRhcHJveHkmc3RyZWFtSWQ9c3RyZWFtMSZkdD0xNjg1MzQ5ODAzMjU1Jk5vZGVJUD05LjIzLjI4Ljg2JmNudD0yJnJ0PTE2ODY2NDc4MDcxMzImcnRtcz0xNjg2NjQ3ODA3MTMyAAAAHwEcbAAAABgxfHdob3xkb2luZ1xuMnx3aG98ZG9pbmcPAQ=="
    }, {
        "index": 3,
        "data": "DwEAAAGItBOxkAAAAAEAdGdyb3VwSWQ9dGVzdF9kYXRhcHJveHkmc3RyZWFtSWQ9c3RyZWFtMSZkdD0xNjg1MzQ5ODAzMDU1Jk5vZGVJUD05LjIzLjI4Ljg2JmNudD0yJnJ0PTE2ODY2NDgzNjk1NDQmcnRtcz0xNjg2NjQ4MzY5NTQ0AAAAHwEcbAAAABgxfHdob3xkb2luZ1xuMnx3aG98ZG9pbmcPAQ=="
    }, {
        "index": 4,
        "data": "DwEAAAGIt74TxQAAAAEAdGdyb3VwSWQ9dGVzdF9kYXRhcHJveHkmc3RyZWFtSWQ9c3RyZWFtMSZkdD0xNjg1MzU5OTA2MDU1Jk5vZGVJUD05LjIzLjI4Ljg2JmNudD0yJnJ0PTE2ODY3MDk4Njc0NjAmcnRtcz0xNjg2NzA5ODY3NDYwAAAAHwEcbAAAABgxfHdob3xkb2luZ1xuMnx3aG98ZG9pbmcPAQ=="
    }]
}
```

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@fuweng11, thanks, I'll fix it

**Comment by gosonzhang** [comment]
The reason is that:
1.  the encoding type "msgEnType" [a] of the data content is placed in the attribute field;
2. the admin_snapshot_message method only returns the content of the data field in the Message;

so, adding the attribute part in the query result can meet this requirement.

I will improve this part of the processing, add the ”attr“ field [b] to carry the attribute information of the Message in the return result of the method

a. https://github.com/apache/inlong/pull/8285
b. ![image](https://github.com/apache/inlong/assets/14038849/165b7f15-e97c-4a48-b6b9-dc370e7e08d9)
