### ISSUE TITLE
[Bug][TubeMQ] Display wrong response message in TubeMQ master web panel

### ISSUE THREAD

**Issue by liaosunny123** [apache/inlong#8717]
### What happened

The TubeMQ Master Web Panel cannot display wrong response.
An incorrect operation is performed, but the front end returns that the operation was successful.

### What you expected to happen

Display err msg when Api response carries errInfo

### How to reproduce

When I make a wrong action:
The Api returns:
<img width="455" alt="a7689767c14e1e58d99ffb7999a95ab" src="https://github.com/apache/inlong/assets/30096937/6dd2ea40-2a7f-459b-add0-190b1799e061">
However, the frontend display:
<img width="667" alt="067e50c4f494e3ace05d200b68bb23c" src="https://github.com/apache/inlong/assets/30096937/03515870-57a0-4a82-9b0d-d392b94a8c1e">

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@liaosunny123, can you elaborate on this Bug? I can't get it, thanks!

**Comment by gosonzhang** [comment]
This place should be caused by the lack of alignment of the console implementation: the new version of the API supports multiple concurrent operations, and the return structure is divided into two parts: whether the operation of this request is successful, and whether each operation item in this request is successful. The console returns only the status of this operation, without subdividing the results of each operation item in the operation.

But, based on the implementation of this console, how some of the unsuccessful operation result sets are displayed on the page, I think it is not easy to modify.

**Comment by liaosunny123** [comment]
> This place should be caused by the lack of alignment of the console implementation: the new version of the API supports multiple concurrent operations, and the return structure is divided into two parts: whether the operation of this request is successful, and whether each operation item in this request is successful. The console returns only the status of this operation, without subdividing the results of each operation item in the operation.
> 
> But, based on the implementation of this console, how some of the unsuccessful operation result sets are displayed on the page, I think it is not easy to modify.

This problem has been fixed in PR #8722 , however there is a detail which should be talked about: https://github.com/apache/inlong/pull/8722#issuecomment-1677160259
